FROM ubuntu
RUN apt-get update
RUN apt-get install -y wget
#CMD wget -O- -q http://ifconfig.me/ip

#CMD echo "AAAAAAAAAAAAA"

#Entrypoint sets the command and parameters that will be executed first when a container is run.
# docker build -t myip -f Dockerfile_ENTRYPOINT .
# docker run myip AAAAAAAAAAAAAAA

# Will run on
#will append everything we pass when running the container

ENTRYPOINT ["echo"]

# Working with ENTRYPOINT AND CMD - CMD is a parameter to ENTRYPOINT
# ENTRYPOINT ["wget", "-O-", "-q"]
# CMD http://ifconfig.me/ip

# Overriding ENTRYPOINT from commandline `--entrypoint`